runtime: python311
env: standard

automatic_scaling:
  min_instances: 1
  max_instances: 10

env_variables:
  PORT: 8080
  FIREBASE_DB_URL: "https://livecode-35eda-default-rtdb.firebaseio.com/"
  JWT_SECRET: "your-production-jwt-secret-here"
  GEMINI_API_KEY: "your-gemini-api-key"
  TWILIO_ACCOUNT_SID: "ACebf7713a50420e71f8809276371d83f6"
  TWILIO_AUTH_TOKEN: "your-twilio-auth-token"
  TWILIO_NUMBER: "+13167471607"
